import '../styles/globals.css';

export const metadata = {
  title: 'ChatGPT',
  description: 'Generated by Asutosh Padhi',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div className='flex'>
          {/* Sidebar */}
          {/* ClientProvider - Notification */}
          <div className='bg-[#343541] flex-1 flex flex-col justify-center items-center'>{children}</div>
        </div>
      </body>
    </html>
  );
}
